#pragma once

enum class TipoRet
{
    TipoRet::OK,
    TipoRet::ERROR_CORREO_EXISTENTE,
    TipoRet::ERROR_PRODUCTO_EXISTENTE,
    TipoRet::ERROR_PRODUCTO_INEXISTENTE,
    TipoRet::ERROR_CATEGORIA_EXISTENTE,
    TipoRet::ERROR_CATEGORIA_INEXISTENTE,
    TipoRet::ERROR_PROVEEDOR_EXISTENTE,
    TipoRet::ERROR_PROVEEDOR_INEXISTENTE,
    TipoRet::ERROR_STOCK_NEGATIVO,
    TipoRet::ERROR_CLIENTE_EXISTENTE,
    TipoRet::ERROR_CLIENTE_INEXISTENTE,
    TipoRet::ERROR_ORDEN_INEXISTENTE,
    TipoRet::ERROR_ORDEN_NO_PENDIENTE,
    TipoRet::ERROR_VENTA_SIN_DETALLES,
    TipoRet::ERROR_STOCK_INSUFICIENTE,
    TipoRet::ERROR_PUNTAJE_INVALIDO,
    TipoRet::ERROR_PRODUCTO_NO_COMPRADO,
    TipoRet::ERROR_CREDENCIALES_INVALIDAS
};
