#pragma once

enum class TipoRet
{
    OK,
    ERROR_CORREO_EXISTENTE,
    ERROR_PRODUCTO_EXISTENTE,
    ERROR_PRODUCTO_INEXISTENTE,
    ERROR_CATEGORIA_EXISTENTE,
    ERROR_CATEGORIA_INEXISTENTE,
    ERROR_PROVEEDOR_EXISTENTE,
    ERROR_PROVEEDOR_INEXISTENTE,
    ERROR_STOCK_NEGATIVO,
    ERROR_CLIENTE_EXISTENTE,
    ERROR_CLIENTE_INEXISTENTE,
    ERROR_ORDEN_INEXISTENTE,
    ERROR_ORDEN_NO_PENDIENTE,
    ERROR_VENTA_SIN_DETALLES,
    ERROR_STOCK_INSUFICIENTE,
    ERROR_PUNTAJE_INVALIDO,
    ERROR_PRODUCTO_NO_COMPRADO,
    ERROR_CREDENCIALES_INVALIDAS,
    ERROR_PROVEEDOR_PRODUCTO_INEXISTENTE,
    ERROR_ORDEN_NO_PENDIENTE,
    ERROR_CANTIDAD_NO_COINCIDE
};
